# -*- coding: utf-8 -*-
#© Ankith M Kashyap
# Form implementation generated from reading ui file 'CountDown.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 527)
        MainWindow.setMinimumSize(QtCore.QSize(318, 527))
        MainWindow.setMaximumSize(QtCore.QSize(318, 527))
        MainWindow.setStyleSheet("background-color: rgb(56, 55, 56);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Headings = QtWidgets.QLabel(self.centralwidget)
        self.Headings.setGeometry(QtCore.QRect(10, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("D3 Euronism Bold italic")
        font.setPointSize(16)
        self.Headings.setFont(font)
        self.Headings.setStyleSheet("color: rgb(151, 255, 32);")
        self.Headings.setAlignment(QtCore.Qt.AlignCenter)
        self.Headings.setObjectName("Headings")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(60, 120, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("border-radius:1px;\n"
"background-color: rgb(80, 80, 80);")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox.setSpecialValueText("")
        self.spinBox.setKeyboardTracking(False)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(10000)
        self.input = QtWidgets.QLabel(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(60, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.Display = QtWidgets.QLCDNumber(self.centralwidget)
        self.Display.setGeometry(QtCore.QRect(50, 180, 211, 111))
        self.Display.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Display.setStyleSheet("")
        self.Display.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Display.setMode(QtWidgets.QLCDNumber.Dec)
        self.Display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Display.setObjectName("Display")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(190, 390, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(22)
        self.Reset.setFont(font)
        self.Reset.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Reset.setStyleSheet("color: rgb(219, 58, 52);\n"
"background-color: rgb(170, 255, 255);\n"
"border-radius: 15px;")
        self.Reset.setFlat(False)
        self.Reset.setObjectName("Reset")
        self.txtDisplay = QtWidgets.QLabel(self.centralwidget)
        self.txtDisplay.setGeometry(QtCore.QRect(20, 300, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(14)
        self.txtDisplay.setFont(font)
        self.txtDisplay.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtDisplay.setStyleSheet("color: rgb(255, 255, 0);")
        self.txtDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDisplay.setObjectName("txtDisplay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 470, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.starts = QtWidgets.QPushButton(self.centralwidget)
        self.starts.setGeometry(QtCore.QRect(20, 390, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(22)
        self.starts.setFont(font)
        self.starts.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.starts.setStyleSheet("color: rgb(219, 58, 52);\n"
"background-color: rgb(170, 255, 255);\n"
"border-radius: 15px;")
        self.starts.setFlat(False)
        self.starts.setObjectName("starts")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        self.menuWelcome = QtWidgets.QMenu(self.menubar)
        self.menuWelcome.setObjectName("menuWelcome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWelcome.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.starts.clicked.connect(self.input_Time)
        self.Reset.clicked.connect(self.reset_All)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Headings.setText(_translate("MainWindow", "Count Down Timer"))
        self.input.setText(_translate("MainWindow", "Input Time(in seconds):"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.Reset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.txtDisplay.setText(_translate("MainWindow", "Time is everything ......!!!"))
        self.label.setText(_translate("MainWindow", "Ver 1.0"))
        self.starts.setText(_translate("MainWindow", "Start"))
        self.starts.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.menuWelcome.setTitle(_translate("MainWindow", "Welcome"))


    def input_Time(self):
        number = self.spinBox.value()
        self.txtDisplay.setText("Time is everything ......!!!")
        self.Display.display(number)
        if number <= 0:
            self.txtDisplay.setText("ERROR : Give Proper Input !!")
        else:
            while number > 0:
                time.sleep(1)
                self.Display.display(number)
                self.Display.repaint()
                print(number)
                number -= 1
                if number == 1:
                    self.txtDisplay.setText("You Were Decieved !!")



    def reset_All(self):
        self.spinBox.setValue(0)
        self.Display.display(0)
        self.txtDisplay.setText("Time is everything ......!!!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
